### ISSUE TITLE
Is there a way to convert Ipv6 to Ipv4?

### ISSUE THREAD

**Issue by jrodrguez08** [whitequark/ipaddr.js#100]
Is there a way to convert Ipv6 to Ipv4? I just need to get a string format Ipv4 from a Ipv6 address.
Is that possible?

**Comment by whitequark** [comment]
Well, not in general, of course. Are you talking about IPv6-mapped IPv4 addresses?

**Comment by jrodrguez08** [comment]
Hi, no, plain IPv6 addresses

**Comment by whitequark** [comment]
That's not possible. There are 79228162514264337593543950336 IPv6 addresses for every IPv4 address.
