### ISSUE TITLE
Some IPv4 Mapped IPv6 Addresses don't parse

### ISSUE THREAD

**Issue by nperriwp** [whitequark/ipaddr.js#101]
The following calls throw exceptions:

ipaddr.parse("::172.26.107.11")
ipaddr.IPv6.parse("::172.26.107.11")

I'm using version 1.7.0.

**Comment by whitequark** [comment]
These aren't IPv4-mapped addresses; IPv4-mapped addresses look like `::ffff:172.26.107.11`.

**Comment by nperriwp** [comment]
It is a deprecated format. See https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses

> A deprecated format for IPv4-compatible IPv6 addresses is ::192.0.2.128.

**Comment by whitequark** [comment]
Yes, these are IPv4-compatible IPv6 addresses. Do you have any particular reason to use them?

**Comment by nperriwp** [comment]
I'm using C++ boost::asio::ip::address_v6::to_string() and then sending the result to this library to make sure it is a valid IP address.

**Comment by whitequark** [comment]
Why does boost::asio use deprecated IP addresses?

Regardless of that, I acknowledge that this is a valid use case, since boost is widely deployed. Do you think you can prepare a PR?

**Comment by nperriwp** [comment]
I agree, boost::asio should not be using deprecated IP addresses.

PR?

**Comment by whitequark** [comment]
Pull request, with a fix for this issue (it should be quite short) and a test.

**Comment by nperriwp** [comment]
Thanks for the quick turn around. I can definitely test it.

I'm a little new to GitHub and haven't created a pull request before. Do I create one before or after the fix?

**Comment by whitequark** [comment]
After. I think this guide can be helpful: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/.

**Comment by whitequark** [comment]
@barakt11 `[::]` is not an IP address. The `[::]` is used in URLs, and the brackets are a part of the URL, not of the IP address. Your URL parsing library should handle those.
