### ISSUE TITLE
Missing "main" property in package.json

### ISSUE THREAD

**Issue by ThermalCube** [whitequark/ipaddr.js#107]
The package.json file is currently missing the "main" property to map to the correct .js file.
The issue has a known hotfix ([https://stackoverflow.com/a/44205882](https://stackoverflow.com/a/44205882)) but it would be great if this rather silly problem could be fixed in the next version.

**Comment by whitequark** [comment]
Can you send a PR? I am not familiar with Webpack.

**Comment by DiscoNova** [comment]
There seems to be "main"-property defined in package.json and it does seem to point to the file I'd expect it to.

I wonder if this issue is still valid?
