### ISSUE TITLE
Add git release tag 0.1.9

### ISSUE THREAD

**Issue by nkbt** [whitequark/ipaddr.js#11]
At the moment when using shrinkwrapping our product build fails since the last version in git is 0.1.8, but npm version is 0.1.9.

Thanks!

**Comment by whitequark** [comment]
Done

**Comment by whitequark** [comment]
The hell is shrinkwrapping? (I stopped writing javascript a few years ago)

**Comment by nkbt** [comment]
> The hell is shrinkwrapping?

Locking down whole tree of dependencies. See `npm shrinkwrap`.

Thanks for quick reply!
