### ISSUE TITLE
:: range is wrong

### ISSUE THREAD

**Issue by barakt11** [whitequark/ipaddr.js#110]
ipaddrJs.parse("::").range() returning 'unspecified' instead of 'loopback'

**Comment by whitequark** [comment]
Because it's not loopback. The loopback address (there's only a single one in IPv6) is `::1`. `::` is precisely unspecified.

**Comment by barakt11** [comment]
Chrome considers [::] as loopback
![alt text](https://image.ibb.co/i548HT/gscreenshot_2018_07_10_121442.png)

**Comment by whitequark** [comment]
[RFC3513 section 2.5.2](https://tools.ietf.org/html/rfc3513#section-2.5.2) says `::` is the unspecified address. That the Linux stack happens to route it to localhost is irrelevant.

**Comment by barakt11** [comment]
Cool :+1:
