### ISSUE TITLE
The license file is missing in the distribution

### ISSUE THREAD

**Issue by honzajavorek** [whitequark/ipaddr.js#113]
```shell
$ ls node_modules/ipaddr.js/
README.md	ipaddr.min.js	lib		package.json
```

I'm not sure how this is possible as all recent versions of npm publish force including the license file automatically. However, this results in the package distribution on npm to be a proprietary, unlicensed code, which nobody who cares about licensing can use as it would be theft against copyright.

@whitequark Could you please make sure the license gets published as well and make a patch version to get this change virally to all projects depending on `ipaddr.js`? Thanks!

**Comment by whitequark** [comment]
> @whitequark It might just be enough to do `npm publish` with npm version >3.7.4 (IIRC) which should take the LICENSE file and bundle it along the rest of the contents appropriately. You can check the result by specting the tarball you get from running the `npm pack` command.

This worked, thanks.

v1.9.0 released.
