### ISSUE TITLE
subnetMaskFromPrefixLength in IPv6

### ISSUE THREAD

**Issue by qin-nz** [whitequark/ipaddr.js#114]
Can you provide subnetMaskFromPrefixLength in IPv6?
e.g.
```
ipaddr.IPv6.subnetMaskFromPrefixLength(64)
```

**Comment by whitequark** [comment]
IPv6 does not use the concept of subnet masks.

**Comment by qin-nz** [comment]
@whitequark Yes, IPv6 doesn't.
In my case, I need know an IPv6 Address is belongs to a prefix.
For example, I want to know 2001:1234::1 belong to 2001:1234::/32 or not.

I can use that method to get subnetMask, and use binary and logic XOR & AND to know it.

**Comment by whitequark** [comment]
You can use the following code for checking for a CIDR match of 2001:db8::1 to 2001:db8:aaa::/48:

    var addr1 = ipaddr.IPv6.parse("2001:db8::1");
    var addr2 = ipaddr.IPv6.parse("2001:db8:aaa::");
    addr1.match(addr2, 48)
