### ISSUE TITLE
loopback ipv6

### ISSUE THREAD

**Issue by michaelfreitag** [whitequark/ipaddr.js#117]
Hi,

I have a request ip and want to match it against a CIDR. I want to validate that the request comes from localhost.

Request IP (Localhost): "::ffff:127.0.0.1"

`var requestIp = ipaddr.parse(request.ip);`
`requestIp.match(ipaddr.parseCIDR('::1/128'))`

=> but this is false? 🤔

Thanks a lot!

**Comment by whitequark** [comment]
I'm not sure what to answer here other than "these are different IP addresses". Your expression essentially checks if `requestIp` is *exactly* `::1` (that's what the `/128` range means), and it is, well, not that. You have to check for IPv4-mapped IPv6 addresses separately, using something like `requestIp.match(ipaddr.parseCIDR('::ffff:127.0.0.1/104'))`.
