### ISSUE TITLE
Support the CIDR notation for subnet matching

### ISSUE THREAD

**Issue by CedricConnes** [whitequark/ipaddr.js#12]
It would be very useful if `address#match` was able to parse the [CIDR notation](http://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#CIDR_notation).

This is already done in [`proxy-addr`](https://github.com/jshttp/proxy-addr/blob/917fa69ae1a4c3e2962d89461b6945538b763b28/index.js#L141) (used by Express to parse the [`trust proxy` setting](http://expressjs.com/api.html#trust.proxy.options.table)), and could maybe be directly integrated to `ipaddr.js`.

**Comment by whitequark** [comment]
Done and published in v1.0.0.

**Comment by CedricConnes** [comment]
Really fast, thanks a lot!

However, `parseCIDR` is only exposed through `ipaddr.IPv4.parseCIDR` and `ipaddr.IPv6.parseCIDR` (but not directly through `ipaddr.parseCIDR` as mentionned in the README).

**Comment by whitequark** [comment]
Fixed

**Comment by CedricConnes** [comment]
Thanks!
