### ISSUE TITLE
Optional prefix size for parseCIDR

### ISSUE THREAD

**Issue by CedricConnes** [whitequark/ipaddr.js#13]
If `parseCIDR` is called without a prefix size, the maximum size could be used by default (subnet of size 1).

For example:
 * IPv4: `parseCIDR("192.168.1.1")` => `[{...}, 32]`
 * IPv6: `parseCIDR("2001:db8:1234::1")` => `[{...}, 128]`

**Comment by whitequark** [comment]
I don't think that's right. `parseCIDR` should do what its name says: parse CIDR notation. A bare IP is not in CIDR notation.

It is easy enough to catch the exception in the client code and adjust.

**Comment by CedricConnes** [comment]
Yes, I see your point. Indeed, `parseCIDR` is not the right place for that.

One could actually write something like this:
```javascript
var cidr;
try {
    cidr = ipaddr.parseCIDR(xxx);
} catch (err) {
    var addr = ipaddr.parse(xxx);
    cidr = [addr, (addr.kind() === 'ipv4') ? 32 : 128];
}
```

But it is boilerplate code, that would perfectly fit in a dedicated module like `ipaddr.js`.
Also, the `try` / `catch` looks a bit hacky here.

**Comment by whitequark** [comment]
I don't see that pattern coming up often enough to warrant an API in ipaddr.js.

**Comment by CedricConnes** [comment]
Okay, no problem.
Thanks for your answers.
