### ISSUE TITLE
Types had become obsolete

### ISSUE THREAD

**Issue by JamesJGoodwin** [whitequark/ipaddr.js#135]
It seems that types had become obsolete for modern TS compiler. Having an issue with this part of code:

```typescript
export const isIpInSubnets = (ip: string, cidrs: Array<string>): boolean => {
    const addr = ipaddr.parse(ip)
    return cidrs.some(cidr => {
        addr.match(ipaddr.parseCIDR(cidr))
        /*   ^^^^^ This expression is not callable.
          Each member of the union type '{ (addr: IPv4, bits: number): boolean; (mask: [IPv4, number]): boolean; } | { (addr: IPv6, bits: number): boolean; (mask: [IPv6, number]): boolean; }' has signatures, but none of those signatures are compatible with each other.ts(2349)*/
    })
}
```

I was able to fix this for myself with a small changes to `ipaddr.js.d.ts`:

```typescript
export class IPv4 extends IP {
    // match(mask: [IPv4, number]): boolean; <--- obsolete definitions
    match(mask: [IPv4 | IPv6, number]): boolean;
}

export class IPv6 extends IP {
    // match(mask: [IPv6, number]): boolean; <--- obsolete definitions
    match(mask: [IPv6 | IPv4, number]): boolean;
}
```

But it feels more like a hack rather than a fix since passing IPv4 subnet to IPv6 class would throw in real life usage.

@raijinsetsu I understand that you wrote this types long time ago but it would be great if you could still come up with a solution here since I'm not that good in TS. With respect.

**Comment by kennethtran93** [comment]
I think the above 'hack' should be fine as a fix as the internal function checks if the kind() is its own kind.
