### ISSUE TITLE
IPv4-mapped IPv6 addresses and IPv4-translated addresses are not taken as valid IPv6 addresses

### ISSUE THREAD

**Issue by alpha1729** [whitequark/ipaddr.js#140]
#examples  ::255.255.255.255  ::ffff:255.255.255.255  ::ffff:0:255.255.255.255 
  IPv6.parse('::255.255.255.255').toByteArray();
//throws error "ipv6 part count should be 8 or 16"

**Comment by whitequark** [comment]
To be clear, IPv4-mapped IPv6 addresses work, what doesn't work is the decimal form.
