### ISSUE TITLE
[BUG] IPv6 Shortening is not right

### ISSUE THREAD

**Issue by avasant21** [whitequark/ipaddr.js#155]
the below toString() operation is wrong.

> ipaddr.parse("2001:0000:0000:0db8:0000:0000:0000:0001").toString();
'2001::db8:0:0:0:1'  --> This format is not the right one

rfc5952: https://www.rfc-editor.org/rfc/rfc5952.txt

4.2.3. Choice in Placement of "::"

When there is an alternative choice in the placement of a "::", the **longest run of consecutive 16-bit 0 fields MUST be shortened** (i.e., the sequence with three consecutive zero fields is shortened in 2001:0:0:1:0:0:0:1). When the length of the consecutive 16-bit 0 fields are equal (i.e., 2001:db8:0:0:1:0:0:1), the first sequence of zero bits MUST be shortened. For example, 2001:db8::1:0:0:1 is correct representation.

So in our case,
IPv6: 2001:0000:0000:0db8:0000:0000:0000:0001
The right shortened representation should have been: 2001:0:0:db8::1

**Comment by Kr0san89** [comment]
@whitequark  can you publish this change on npm? thanks

**Comment by Kr0san89** [comment]
unfortunately on npm it is still 2.0.1 i guess you still need to publish?

**Comment by whitequark** [comment]
Oh, it's because they started requiring OTPs and didn't do error messages well. Published now.
