### ISSUE TITLE
Failure in parsing ipv4 with leading 0

### ISSUE THREAD

**Issue by alinex** [whitequark/ipaddr.js#16]
See the coffeescript code below:

    coffee> ipaddr.parse '192.12.1.1'
    { octets: [ 192, 12, 1, 1 ] }
    coffee> ipaddr.parse '192.012.1.1'
    { octets: [ 192, 10, 1, 1 ] }

Why is the address wrong if i add a leading 0?

**Comment by whitequark** [comment]
Octal. Not a bug but standard behavior in Unix `inet_ntoa`. E.g.:
```
$ ping 192.012.1.1
PING 192.012.1.1 (192.10.1.1) 56(84) bytes of data.
```

**Comment by vitaly-t** [comment]
This is one of the most confusing address interpretations. A good solution should allow for a flag to auto-trim zeroes before conversion, to avoid the confusion.

**Comment by whitequark** [comment]
It may be confusing, but diverging from the ubiquitous Unix's `inet_ntoa` would be just more confusing.

Use IPv6, it has no such problems ;p
