### ISSUE TITLE
IPV4 isValid doesn't validate whether it has 4 fields with 3 digits

### ISSUE THREAD

**Issue by hari1447** [whitequark/ipaddr.js#164]
The IPV4 should contain 4 fields with max. 3 digit each validation will be good to have.

**Comment by noro03** [comment]
are there any updates?

**Comment by whitequark** [comment]
Use `IPv4.isValidFourPartDecimal`.

**Comment by noro03** [comment]
> Use `IPv4.isValidFourPartDecimal`.
thanks for the answer and
what if I am using ipAddr.isValid?
