### ISSUE TITLE
How to use ipaddr.subnetMatch() for 2 ip ranges?

### ISSUE THREAD

**Issue by RuthiCohen** [whitequark/ipaddr.js#166]
Hi, 
Im using this package in order to test whether an ip is in range or not.
I get 2 ips for some range(first & last).
I've seen the method of :
`const rangeList = {
  documentationOnly: [ ipaddr.parse('2001:db8::'), 32 ],
  tunnelProviders: [
    [ ipaddr.parse('2001:470::'), 32 ], // he.net
    [ ipaddr.parse('2001:5c0::'), 32 ]  // freenet6
  ]
};
ipaddr.subnetMatch(ipaddr.parse('2001:470:8:66::1'), rangeList, 'unknown');
`
But I don't understand what is **documentationOnly** for? because we get the **tunnelProviders** for the ips ranges, right?
Thanks in advance!

**Comment by Johann150** [comment]
`documentationOnly` and `tunnelProviders` are arbitrary names that you can choose yourself.

`ipaddr.subnetMatch` will return the name that matches. If none matches, the 3rd argument (in this case `'unknown'`)  will be returned instead.

**Comment by whitequark** [comment]
Thanks @Johann150!
