### ISSUE TITLE
"toString.call" is missing "Object.prototype" and fails in IE11

### ISSUE THREAD

**Issue by jkellerer** [whitequark/ipaddr.js#17]
Hi whitequark,

First of all thanks for this great piece of software!

While using it inside a browser environment I found that IE11 does not support calling "toString.call".
The relevant code is in line 34:
 ```coffeescript
    if rangeSubnets[0] && toString.call(rangeSubnets[0]) != '[object Array]'
```
The problem is that "toString" without specifying "Object::" works in Webkit and Firefox but not in IE.
Looking at "isArray" from AngularJS you'll find that their "toString" is initialized from "Object.prototype.toString" (the logic is however the same).

The following change fixed the problem:
 ```coffeescript
    if rangeSubnets[0] && Object::toString.call(rangeSubnets[0]) != '[object Array]'
```

(All test still pass afterwards)

jk

**Comment by whitequark** [comment]
As a side note, `::` is a Microsoft extension.
