### ISSUE TITLE
Some IPv4 Mapped IPv6 Addresses don't parse

### ISSUE THREAD

**Issue by liaorg** [whitequark/ipaddr.js#171]
The following calls throw exceptions:

ipaddr.IPv6.parse("FFFF::255.255.255.255")
throw :
Error: ipaddr: the address has neither IPv6 nor IPv4 format

but
ipaddr.IPv6.parser("FFFF::0:255.255.255.255") is ok!

![QQ图片20231007143751](https://github.com/whitequark/ipaddr.js/assets/7478660/d0443f6f-4b0f-40d4-a7fc-7cf0cc07dffc)

I'm using version 2.1.0

**Comment by whitequark** [comment]
Yep that's a bug.

**Comment by liaorg** [comment]
> Yep that's a bug.

can you fix it , and when? thanks @whitequark

**Comment by whitequark** [comment]
This library is passively maintained: if an acceptable fix is proposed I will merge it and release a new version. Otherwise no.

**Comment by takapiro99** [comment]
@liaorg 

It looks like the ipv6 parsing logic has changed in v2.2.

According to the [RFC](https://www.rfc-editor.org/rfc/rfc4291#section-2.5.5.2), the format of "IPv4-Mapped IPv6 Address" is `::FFFF:0:0/96`. I think the format of `FFFF::0:0/96` is a violation.

I am not a network engineer, so I don't know the actual situation,　but wouldn't it be better to fix the logic of the parsing according to the RFC?

If you have any other background, please let me know.
