### ISSUE TITLE
Having issue with Windows IPV6  in IPV4 compatible format

### ISSUE THREAD

**Issue by alberk8** [whitequark/ipaddr.js#180]
The original IPV6 is ::ffff:192.168.1.10 but the convert to bytearray and then back to ipaddr format does not get back the original format 
Instead I am getting  ::ffff:c0a8:10a   

Is this a bug?

```
var myip = ipaddr.parse("::ffff:192.168.1.10");
var myip_byte = myip.toByteArray();
var convert_back = ipaddr.fromByteArray(myip_byte).toString();
 
console.log(convert_back);
```

**Comment by whitequark** [comment]
These are the same IP addresses, even if the representation is a little different. You will get a similar effect if you expand the `::` and roundtrip the address.
