### ISSUE TITLE
IPv4 and IPv6 validation not working properly

### ISSUE THREAD

**Issue by DusanMadar** [whitequark/ipaddr.js#25]
### IPv4
`ipaddr.isValid('10.168.0001.100')` returns `true`.

### IPv6
`ipaddr.isValid('02001:0000:1234:0000:0000:C1C0:ABCD:0876')` returns `true`.
`ipaddr.isValid('2001:0000:1234:0000:00001:C1C0:ABCD:0876')` returns `true`.

I am comparing results and testing examples from here: http://formvalidation.io/validators/ip/

**Comment by whitequark** [comment]
Actually, `10.168.0001.100` is valid according to the (admittedly loose) definition of IPv4 validation that I use, that is to say, inet_aton:
```
$ ping 192.0000001.1.1
PING 192.0000001.1.1 (192.1.1.1) 56(84) bytes of data.
^C
```

**Comment by whitequark** [comment]
Similarly, your IPv6 addresses are also valid according to `inet6_aton`:
```
$ ping6 02001:0000:1234:0000:0000:C1C0:ABCD:0876
PING 02001:0000:1234:0000:0000:C1C0:ABCD:0876(2001:0:1234::c1c0:abcd:876) 56 data bytes
^C
```

I am not particularly fond of all the obscure forms that `inet*_aton` recognize, but I am not sure I want to make this breaking change either. Please reopen if you have some good argument about this.

**Comment by whitequark** [comment]
See `ipaddr.IPv4.isValidFourPartDecimal` in the 1.2.0 release.
