### ISSUE TITLE
Validate IP Range

### ISSUE THREAD

**Issue by keverw** [whitequark/ipaddr.js#28]
I have a module that relies on ipaddr.js, I got a request for the ability to validate ranges. Is that possible with ipaddr.js? Be a nice extra addon.

https://github.com/keverw/range_check/issues/9

**Comment by whitequark** [comment]
You can wrap `ipaddr.parseCIDR` in a try..catch.

**Comment by keverw** [comment]
Thanks for the reply. I did this but keep getting false. 

````
function valid_range(range)
	{
		try {
			var cidr = ipaddr.parseCIDR(range);

			console.log(range);
			
			return true;
		} catch(err) {
			return false;
		}

	}
```

Here's the test code:
```
console.log(rangeCheck.valid_range('2001:db8::/32')); //true
console.log(rangeCheck.valid_range('10.0.0.0/8')); // true
console.log(rangeCheck.valid_range('qwerty')); // false
```

**Comment by whitequark** [comment]
What's the `err`?

**Comment by keverw** [comment]
[TypeError: ipaddr.parseCIDR is not a function]

**Comment by whitequark** [comment]
Well, I'm pretty sure you did something wrong. https://github.com/whitequark/ipaddr.js/blob/master/src/ipaddr.coffee#L371

**Comment by keverw** [comment]
Hmm,  I see what I did... Not using the latest version. Went to put 1.1.0 in but accidentally put it in my actual version of my module.

**Comment by keverw** [comment]
Oh and looks like 0.0.6 is the latest on NPM.

**Comment by whitequark** [comment]
![1371](https://cloud.githubusercontent.com/assets/54771/10727635/6a49f76e-7bec-11e5-8bb3-0ce0596d8ad4.png)

**Comment by keverw** [comment]
Ops, looked at ipaddr instead. Okay, finally got the lastest version. A bit sleepy, but I think I'm on the right track. Sorry for the confusion.

**Comment by keverw** [comment]
Sweet, the valid_range function works now.

**Comment by keverw** [comment]
Thanks for the help btw :+1:  It's working fine. I just feel a bit stupid right now, but glad we got it!
