### ISSUE TITLE
Readme out of sync with master

### ISSUE THREAD

**Issue by audrummer15** [whitequark/ipaddr.js#40]
The readme mentions fromByteArray() method, and I see it in the coffee script. However, it's not in the exported ipaddr object. Is this being fixed soon?

EDIT: It appears the ipaddr.js file in lib/ has not been compiled from ipaddr.coffee lately. Also, the repository's master branch is totally out of sync with the version installed from npm.

**Comment by whitequark** [comment]
1.1.0 pushed and released to npm.

Incidentally, the way in which you ask me to perform labor for free, such as in "Is this being fixed **soon**?", comes off as nagging and entitled. I suggest you knock that off.
