### ISSUE TITLE
Cannot validate IPv4-Mapped IPv6 Addresses correctly

### ISSUE THREAD

**Issue by JIM-CHEN** [whitequark/ipaddr.js#43]
It can identify isIPv4MappedAddress but cannot catch invalid IPv4 like ::FFFF:222.1.41.9000

ipaddr.IPv6.isValid('::FFFF:222.1.41.9000') will return true.

**Comment by whitequark** [comment]
Good catch.

**Comment by whitequark** [comment]
Fixed in 5c52dae107.
