### ISSUE TITLE
IPv4 validation not working properly

### ISSUE THREAD

**Issue by rskvirskiy** [whitequark/ipaddr.js#44]
ipaddr.IPv4.isValid("1231233") returns true .
But actually this is not valid IPv4.

**Comment by whitequark** [comment]
Nope, it is, according to inet_aton, which is the language that ipaddr.js recognizes: http://linux.die.net/man/3/inet_aton

**Comment by whitequark** [comment]
See `ipaddr.IPv4.isValidFourPartDecimal` in the 1.2.0 release.
