### ISSUE TITLE
ipv4 validate has error in some cases

### ISSUE THREAD

**Issue by light049** [whitequark/ipaddr.js#45]
1. ipaddr.IPvX.isValid('5') 
2. ipaddr.IPvX.isValid('0000.0000.00000.00') 
3. ipaddr.IPvX.isValid('1.1.1.00200')')

All should be false

**Comment by whitequark** [comment]
Duplicate of #44.

**Comment by whitequark** [comment]
See `ipaddr.IPv4.isValidFourPartDecimal` in the 1.2.0 release.
