### ISSUE TITLE
Feature: CIDR first and last IP in a range

### ISSUE THREAD

**Issue by keverw** [whitequark/ipaddr.js#46]
I'm getting a list of CIDRs and wanting to get the first and last IP address to store in the database. Any easy way to get the first and last IP using this module? I found one that could do it but v6 results would incorrectly return 255.255.255.255

**Comment by whitequark** [comment]
Not currently.

**Comment by keverw** [comment]
Oh. I was hoping there was a chance they're was already a lower level API as part of this to get it I didn't know about.

I found out how to do it in PHP: http://stackoverflow.com/questions/10085266/php5-calculate-ipv6-range-from-cidr-prefix - wonder how hard it would be to port to JS. I know there's PHP.js too. So I figured I could probably hack somthing together if really needed but I know it's not really my expertise.

**Comment by whitequark** [comment]
Nah, that's simple. An IPv4 address consists of four octets, an IPv6 address consists of eight 16-bit parts.  For a CIDR mask `/n`, make a new address with n least significant (rightmost) bits filled with ones. The first address is `addr & (~mask)`, the last address is `addr | mask`, where the bitwise operations are performed octet-by-octet or part-by-part.

**Comment by keverw** [comment]
A bit over my head but attempting to turn it into code. What would I put for addr? Using it in a string is no luck, I was thinking calling ipaddr.parseCIDR first and then do somthing with the parts list maybe.

**Comment by whitequark** [comment]
Exactly right. For IPv4 addresses it's `ipaddr.parseCIDR(...)[0].octets`, for IPv6 addresses it's `.parts`. You can distinguish them with typeof.

**Comment by keverw** [comment]
I wrote this so far. Getting back 0's but I feel like it's close. I think the problem is using the array itself when doing the bitmasking part. I'm thinking probably the numbers for each type needs combined some how? hmm. This feels like solving a puzzle

```js
var ipaddr = require('ipaddr.js');

function cidr(value)
{
	var result = {
		valid: false
	};

	try {
		var parse = ipaddr.parseCIDR(value);

		var parts = [];
		var n = parse[1];

		var itemOne = parse[0];

		if (typeof itemOne.octets == 'object') //IPv4
		{
			console.log('v4', itemOne.octets & (~n));
		}
		else if (typeof itemOne.parts == 'object') //IPv6
		{
			console.log('v6', itemOne.parts & (~n));
		}
		else
		{
			return result;
		}

	} catch(err) {
		return result;
	}

}

console.log(cidr('lol'));
console.log(cidr('2001:218:2005:8000::/49'));
console.log(cidr('1.0.0.0/24'));
```

**Comment by whitequark** [comment]
> if (typeof itemOne.octets == 'object') //IPv4

Sorry, I meant instanceof. `if (itemOne instanceof ipaddr.IPv4)`

> I'm thinking probably the numbers for each type needs combined some how?

Yes. You also can't use just `n` as that's not a mask, you need to expand it, as I've described above.

**Comment by keverw** [comment]
Hmm interesting. I wonder if `.join` on the octets/parts maybe. 

> For a CIDR mask /n, make a new address with n least significant (rightmost) bits filled with ones.

Hmm a little over my head. but this looks like how to do it in C? Wonder if mask_for_n_bits function someone wrote is what I'd want. It seems like it would be trivial to rewrite into JS. http://stackoverflow.com/questions/12416639/how-to-create-mask-with-least-significat-bits-set-to-1-in-c

**Comment by keverw** [comment]
I'm still stuck on this. I asked another programming friend about it and they knew how to do it for IPv4 but said 

>  "The first address is addr & (~mask), the last address is addr | mask" was incorrect.
> "first addr is: addr & mask"
> "last addr is: addr & mask + !mask"

Maybe the mask you mentioned is IPv6 only, and his is IPv4? I was assuming it was the same for both, but maybe not.

So being really frustrated, and confused as I'm not an expert on this topic and wanting to move on with my project. I went to search Google, instead of NPM and after a couple of tries I found https://github.com/beaugunderson/ip-address which solves my problem and I can continue forward with my project.

I really appreciate the help so. I'm going to leave this issue open in case you want to add a higher level function for this in the future. If not interested, you can close this and this can serve as a reference for anyone else looking for the same thing.
