### ISSUE TITLE
Doesn't support SIIT

### ISSUE THREAD

**Issue by noway421** [whitequark/ipaddr.js#47]
As per wikipedia:

> Stateless IP/ICMP Translation (SIIT) translates between the packet header formats in IPv6 and IPv4. The SIIT method defines a class of IPv6 addresses called IPv4-translated addresses. They have the prefix ::ffff:0:0:0/96 and may be written as ::ffff:0:a.b.c.d, in which the IPv4 formatted address a.b.c.d refers to an IPv6-enabled node. The prefix was chosen to yield a zero-valued checksum to avoid changes to the transport protocol header checksum

SIIT addresses are not parsed correctly

>::ffff:127.0.0.1
>IPv6 { parts: [ 0, 0, 0, 0, 0, 65535, 32512, 1 ] }

should evaluate to 127.0.0.1

**Comment by whitequark** [comment]
It does in fact, it just does not perform conversion automatically; if you're parsing an IPv6 address, you get an IPv6 address structure back. See ipaddr.IPv6.isIPv4MappedAddress and ipaddr.IPv6.toIPv4Address.
