### ISSUE TITLE
No Range for Carrier-Grade NAT / LSN

### ISSUE THREAD

**Issue by coolaj86** [whitequark/ipaddr.js#49]
I'm not sure what string you'd like to use to define it, but ipv4 is missing the range (`100.64.0.0/10`) for cgn/lsn.

```js
var ipaddr = require('ipaddr.js');

ipaddr.parse('100.64.100.100').range()

// says 'unicast', but should be 'cgn' or 'lsn' or similar
```

See https://en.wikipedia.org/wiki/Carrier-grade_NAT

**Comment by whitequark** [comment]
Sure. Can you send a PR? Call it `carrierGradeNAT`.

**Comment by coolaj86** [comment]
How about `carrierGradeNat` so that the name is portable between programming languages and wire protocols (i.e. it doesn't have to be manually translated to `carrier_grade_nat` from the automatic `carrier_grade_n_a_t`)?

**Comment by whitequark** [comment]
Sure.

**Comment by coolaj86** [comment]
Thanks for pulling that in. Will you tag it as v1.2.1 and republish?

**Comment by whitequark** [comment]
Done (as 1.3.1 because it's a feature)

**Comment by coolaj86** [comment]
Thanks.
