### ISSUE TITLE
Leading 0's cause parsing havoc

### ISSUE THREAD

**Issue by mikegrima** [whitequark/ipaddr.js#52]
Hello!

I noticed that there are oddities around parsing of IPs if there are leading 0's. For example, if given an IP that looks like this: `0192.168.001.002`, this get's parsed into: `1.168.1.2`.

Haven't dug into the code too much. Anything off the top of your head that might be causing this behavior? Essentially, the leading 0's should be truncated.

**Comment by mikegrima** [comment]
I should have probably read this #16 before filing an issue :P

**Comment by whitequark** [comment]
Duplicate of #44.
