### ISSUE TITLE
Is there a functionality to return broadcast / network addresses given IP address and netmask? 

### ISSUE THREAD

**Issue by anchat1990** [whitequark/ipaddr.js#53]

**Comment by whitequark** [comment]
Not really!

**Comment by anchat1990** [comment]
I have a pull request in for this :)

**Comment by anchat1990** [comment]
Hello - just wondering if the version needs to be bumped in package.json for the npm registry to be updated with this change?

**Comment by whitequark** [comment]
`+ ipaddr.js@1.4.0`
