### ISSUE TITLE
subnetMatch cannot handle hybrid IPv4/IPv6 scenarios

### ISSUE THREAD

**Issue by bittrance** [whitequark/ipaddr.js#56]
Use case: I have a list with JSON-transcribed NetFlow packets. These packets include both IPv4 and IPv6 traffic and I want to aggregate them on their net. Many of the IP ranges have both an IPv4 and an IPv6 prefix.

The natural thing to do would be to build a table containing both IPv4 and IPv6 prefixes:
```javascript
var table = {
  "network a": [ ipaddr.parseCIDR('123.0.0.0/24'), ipaddr.parseCIDR('2001:3243:123::/64') ],
  ...
};
```
However, on trying to use such a map, `subnetMatch` will throw errors:
```
Error: ipaddr: cannot match ipv4 address with non-ipv4 one
    at IPv4.ipaddr.IPv4.IPv4.match (/Users/quest/projects/external/ipaddr.js/lib/ipaddr.js:87:15)
    at Object.ipaddr.subnetMatch (/Users/quest/projects/external/ipaddr.js/lib/ipaddr.js:46:27)
```
Since the error is generic, it would be hard to catch this particular case without fiddly substring matching.

It seems counter-intuitive and cumbersome to have to build two separate lookup tables.

I'll be happy to supply a PR, but I realize that this behaviour has been there for 6 years and so dependencies can be expected to depend on it. Would you be open to a PR and if so, what solution would you prefer? An `instanceof` guard in `subnetMatch` or a separate `subnetMatchHybrid` method?

**Comment by whitequark** [comment]
> or a separate subnetMatchHybrid method?

The latter seems fine.
