### ISSUE TITLE
IPv6 prefixLengthFromSubnetMask

### ISSUE THREAD

**Issue by silverwind** [whitequark/ipaddr.js#59]
I noticed this method is only there for IPv4 but missing for IPv6. Can it be added for IPv6 too? It's useful to parse subnet masks from Node.js's `os.networkInterfaces()`, for example:

````js
{ address: 'fe80::1',
  netmask: 'ffff:ffff:ffff:ffff::',
  family: 'IPv6',
  mac: '00:00:00:00:00:00',
  scopeid: 1,
  internal: true }
````

**Comment by whitequark** [comment]
Sure, PRs welcome.

**Comment by silverwind** [comment]
Okay, I'll take this.
