### ISSUE TITLE
IPv6 zone index support

### ISSUE THREAD

**Issue by silverwind** [whitequark/ipaddr.js#60]
Link-local addresses can contain a zone index where`%` and some identifier is appended to the address, see https://en.wikipedia.org/wiki/IPv6_address#Link-local_addresses_and_zone_indices. I think you can just ignore them by doing `input.replace(/%.+/, '')`. Currently, they fails to parse:

````js
> require("ipaddr.js").parse("e80::%utun0")
Error: ipaddr: the address has neither IPv6 nor IPv4 format
````

**Comment by whitequark** [comment]
Not quite:

>   An implementation MAY support other kinds of non-null strings as
>   <zone_id>.  However, the strings must not conflict with the delimiter
>   character.  The precise format and semantics of additional strings is
>   implementation dependent.

So it should be `replace(/^([^%]+)%[^%]+$/, '\1'`. PRs with tests welcome.

**Comment by silverwind** [comment]
It might be useful to retain the `zone_id` on the `addr` object. Maybe as `addr.zone_id`?

**Comment by whitequark** [comment]
> It might be useful to retain the zone_id on the addr object. Maybe as addr.zone_id?

Hm, sure. As `addr.zoneID`.

Oh and keep the following in mind when implementing, the CIDR parser should also correctly handle zone indexes:

> For example, a link-local prefix fe80::/64 on the second link can be represented as follows:
>
>     fe80::%2/64
