### ISSUE TITLE
Browser support intentions? ES5 support?

### ISSUE THREAD

**Issue by JamesMGreene** [whitequark/ipaddr.js#64]
I'm not sure if you are aware of this but this library's browser support is actually pretty limited due to CoffeeScript compiling down into some ES2015 syntax that is not widely supported in older versions.  The use of [`Array.prototype.fill`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#Browser_compatibility), in particular, completely eliminates support for any version of IE or Opera, as well as some mobile browsers -- unless the consumer also utilizes some ES2015 polyfills to inject that missing method.

I would suggest that this library should either (a) mention that so consumers know they must polyfill `Array.prototype.fill`, or else (b) switch to not use that method at all.  Personally, I would prefer the latter as the usage of `fill` in this module is so limited that it would be easy to just replace it with a static value like `[0,0,0,0]`.

Thoughts?  Happy to submit a PR for either.

**Comment by whitequark** [comment]
> I'm not sure if you are aware of this but this library's browser support is actually pretty limited due to CoffeeScript compiling down into some ES2015 syntax that is not widely supported in older versions.

Looks like this was a consequence of upgrading CoffeeScript. Would you mind going through history and reverting that? I think it had some fallout because of another library's version not being restricted enough; if tests pass I'll accept your PR.

**Comment by JamesMGreene** [comment]
Looks like it's been that way since that function (`subnetMatch`) was originally implemented, so I don't think it's the CoffeeScript upgrade that broke it.  I'm submitted a bug to CoffeeScript to clarify the intentions here as I'm not too familiar with them.

**Comment by JamesMGreene** [comment]
CoffeeScript collaborators answer: transpiling ES2015 features is not an intended goal. :-1:

**Comment by JamesMGreene** [comment]
Submitted PR #66.

**Comment by JamesMGreene** [comment]
Closed PR #66, included in PR #74.
