### ISSUE TITLE
API symmetry: add `ipaddr.IPv4.prototype.toNormalizedString` method

### ISSUE THREAD

**Issue by JamesMGreene** [whitequark/ipaddr.js#67]
For API symmetry, it would be nice to add a `ipaddr.IPv4.prototype.toNormalizedString` method to match the IPv6 one.  I'd imagine it just is the same as `toString`, i.e.

```js
ipaddr.IPv4.prototype.toNormalizedString = ipaddr.IPv4.prototype.toString;
```

**Comment by JamesMGreene** [comment]
Submitted PR #71.

**Comment by JamesMGreene** [comment]
P.S. I'm fine if you don't agree with this one.

**Comment by whitequark** [comment]
This one seems fine.
