### ISSUE TITLE
isValid('1') returns true 

### ISSUE THREAD

**Issue by jakarii** [whitequark/ipaddr.js#7]
```
var ipaddr = require('ipaddr.js'),
    ip = '1';

if (ipaddr.isValid(ip)){
    var addr = ipaddr.parse(ip);
}
```

Error: ipaddr: ipv6 part count should be 8
    at new IPv6 (/.../ipaddr.js:155:15)
    at Function.ipaddr.IPv4.parse.ipaddr.IPv6.parse (/.../ipaddr.js/lib/ipaddr.js:374:12)

**Comment by stephencattaneo** [comment]
The 'an integer is a valid IPv4' behavior is a little weird. I've had to do the following for my code:

    function isValidIp(ip) {
      return /^\d+$/.exec(ip) ? false : ipaddr.isValid(ip);
    }

Ruby's IPAddr module doesn't treat single integers as valid IPv4:

    1.9.3-p547 :004 > IPAddr.new '1'
    ArgumentError: invalid address

Neither does postgres:
  
    # select inet '1';
    ERROR:  invalid input syntax for type inet: "1"
    LINE 1: select inet '1';

Meanwhile python's behavior is consistent with C:

    Python 2.7.5 (default, Mar  9 2014, 22:15:05)
    [GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import socket
    >>> socket.inet_aton('1')
    '\x00\x00\x00\x01'

So I guess its mostly consistent, but I'd imagine for a lot of people this will be a source of bugs

**Comment by komaira** [comment]
What was the solution for this? I'm currently having an issue where any number/string being passed into .isValid() returns true?
