### ISSUE TITLE
`ipaddr.IPv4.subnetMaskFromPrefixLength(32)` throws Error

### ISSUE THREAD

**Issue by JamesMGreene** [whitequark/ipaddr.js#73]
`ipaddr.IPv4.subnetMaskFromPrefixLength(32)` throws Error rather than returning `"255.255.255.255"`

**Comment by whitequark** [comment]
This isn't actually a legal subnet mask (neither is 255.255.255.254 by the way, a subnet needs to have at least 4 IPs in it). It should be an error, although a different one; adjust the condition?

**Comment by JamesMGreene** [comment]
Hmm... I'm not sure how to take this one.  `/31` and `/32` do translate to valid masks but it is true that they are not usable subnets as they do not have any effective hosts available.

If it were my own module, I think I'd still want the `/31` and `/32` to return the subnet mask anyway. However, if you still disagree, I can still make a PR for your suggested approach anyway.

**Comment by whitequark** [comment]
OK, let's return valid subnet masks from them because otherwise it'd be a breaking change, semver-wise.

**Comment by JamesMGreene** [comment]
Good call. :+1:
