### ISSUE TITLE
Normalizing IPv6 CIDRs, and getting first and last effective host addresses from IPv4 and IPv6

### ISSUE THREAD

**Issue by JamesMGreene** [whitequark/ipaddr.js#76]
I've come to the realization that I believe #68, #69, #70, and #75 (all related to IPv6 CIDR methods) were all likely closed due to some communication issues over mismatched terminology.

My real usage goal for them was to be able to normalize an IPv6 CIDR to use its first effective host address rather than whatever address was originally provided, much like I can already do for IPv4 CIDRs using their network address, e.g.

```js
ipaddr.processCIDR('ac00::1/24')  // => [ ipaddr.parse('ac00::'), 24 ]

ipaddr.processCIDR('1.2.3.4/5')   // => [ ipaddr.parse('0.0.0.0'), 5 ]
```

As such, I'd like to add some methods to support that cause.  PR forthcoming.

**Comment by whitequark** [comment]
See #77.
