### ISSUE TITLE
IPv4 zone index

### ISSUE THREAD

**Issue by silverwind** [whitequark/ipaddr.js#87]
I was wondering if these exist and according to [rfc4001](https://tools.ietf.org/html/rfc4001) they actually do:

````
InetAddressIPv4z ::= TEXTUAL-CONVENTION
    DISPLAY-HINT "1d.1d.1d.1d%4d"
    STATUS       current
    DESCRIPTION
        "Represents a non-global IPv4 network address, together
         with its zone index:

           Octets   Contents         Encoding
            1-4     IPv4 address     network-byte order
            5-8     zone index       network-byte order

         The corresponding InetAddressType value is ipv4z(3).

         The zone index (bytes 5-8) is used to disambiguate identical
         address values on nodes that have interfaces attached to
         different zones of the same scope.  The zone index may contain
         the special value 0, which refers to the default zone for each
         scope.
````
While I know no use case for them, I think we should support them for completeness sake.

**Comment by whitequark** [comment]
As far as I know it's functionally impossible to use scoped addresses with IPv4 because the sockaddr_in structure on all of Windows, Linux and macOS does not have the zone index field. So I really see no point in adding them, it would just create confusion for our users.
