### ISSUE TITLE
ES6-style import declarations don't work in TypeScript

### ISSUE THREAD

**Issue by TedDriggs** [whitequark/ipaddr.js#88]
Environment: Typescript@2.5.2

```typescript
import ipaddr from 'ipaddr.js';

ipaddr.parse("1.2.3.4"); // error; cannot call function 'parse' of undefined
```

```typescript
const ipaddr = require('ipaddr.js');

ipaddr.parse("1.2.3.4"); // works
```

The `tsconfig.json` used for this was:

```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es2016",
        "strictNullChecks": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

Mostly, I was surprised that the library isn't recognized as a module unless imported via `require`. This also makes declaring a `.d.ts` file more difficult; the one I'd started worked with the ES6-style import but not with the `require` declaration.

**Comment by whitequark** [comment]
I know basically nothing about post-2012 JavaScript. Help me out?

**Comment by TedDriggs** [comment]
I'm not 100% sure what's happening yet either; still investigating.

**Comment by mooyoul** [comment]
1. import module like this way:
```typescript
import * as ipaddr from 'ipaddr.js';
```

2. declare module like below:
```typescript
// this filename should have .d.ts extension
declare module 'ipaddr.js' {
  type IPVersion = "ipv4" |  "ipv6";

  interface IPAddr {
    type: () => IPVersion;
    octet: number[];
  }

  interface IPAddrModule {
    parse: (ip: string) => IPAddr
  }

  const module: IPAddrModule;
  export = module;
}
```

**Comment by raijinsetsu** [comment]
I opened #93 to get type definitions added to this project. Email me if you want a more complete definition than above.

**Comment by whitequark** [comment]
#93 should have fixed this.
