### ISSUE TITLE
Cannot find module error while building docker container

### ISSUE THREAD

**Issue by spurreiter** [whitequark/ipaddr.js#89]
I am building a docker container with node@6.11.4 / npm@3.10.10 which contains an `express` server using `proxy-addr` which itself uses `ipaddr.js` as dependency. 
Unfortunately at the starting the container the server stops with a `Error: Cannot find module 'ipaddr.js`. 

Interestingly the installed `package.json` file of `ipaddr.js` inside the container is lacking the `main` key.
Changing `main` to point to `./lib/ipaddr.js` solves the issue.

So some `npm` magic seams to strip of the `main` entry as it does not find the file assigned.

**Comment by spurreiter** [comment]
Thanks a lot for the quick merge. Would you mind publishing a new patch on npm?

**Comment by lancecarlson** [comment]
I just ran into this issue as well. Making the change to package.json as @spurreiter did solved the issue but means I have to freeze this node_module somehow. PLEASE make a release asap. ipaddr.js is a dep from proxy-addr which is dep for express. I guarantee you a lot more people will start having issues if this isn't patched quick and subsequent dep's not updated as well.

**Comment by whitequark** [comment]
Fine. 1.5.3
