### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by raijinsetsu** [whitequark/ipaddr.js#93]
I have created a Typescript definition file for this module. Any interest in including it in the module itself? Typescript can now rely on the "typings" property in the package.json to load the typings.

If not, I'll proceed with getting this into DefinitelyTyped so it can be available as a separate module via NPM.

**Comment by whitequark** [comment]
Sure, go ahead

**Comment by kornicameister** [comment]
@whitequark Any chance it might be released soon ?

@raijinsetsu did you made a progress in putting this to `DefinitelyTyped` ?

**Comment by raijinsetsu** [comment]
@kornicameister
PR #94 added the type script definitions to this repo. There is no reason to put them into DefinitelyTyped.

**Comment by whitequark** [comment]
Released v1.6.0

**Comment by kornicameister** [comment]
You're too kind ;-)

**Comment by gyzerok** [comment]
Hi @whitequark!

It seems that you made a new tag for 1.6.0 but haven't published it to npm. Can you do it, please? 😃

**Comment by whitequark** [comment]
Oops! Done.
