### ISSUE TITLE
isValid methods for IPv4 returns True if one of the octets starts with 0

### ISSUE THREAD

**Issue by vlipovoy** [whitequark/ipaddr.js#96]
Examples:
The output is true:
ipaddr.IPv4.isIPv4('10.10.10.000000112')
ipaddr.IPv4.isIPv4('00010.10.10.000112')
ipaddr.IPv4.isIPv4('000192.0168.10.000112')

Is this expected behaviour?

**Comment by whitequark** [comment]
Duplicate of #44.
