### ISSUE TITLE
Returns true on ip's with "00000" at the start

### ISSUE THREAD

**Issue by johnfrades** [whitequark/ipaddr.js#98]
Hi, I just want to ask, this code
`ipaddr.IPv4.isValidFourPartDecimal('0000000192.168.0.21')`
still returns true. I found one issue that's related to this and already been closed, the author told to use `IPv4.isValidFourPartDecimal` 

But it still returns true on`ipaddr.IPv4.isValidFourPartDecimal('0000000192.168.0.21')`

**Comment by whitequark** [comment]
Yes, this is a bug. Do you think you could alter https://github.com/whitequark/ipaddr.js/blob/master/src/ipaddr.coffee#L417 to use `/^[1-9]\d*(\.[1-9]\d*){3}$/` as a regexp and write a test, please?

**Comment by whitequark** [comment]
Sure!

**Comment by johnfrades** [comment]
Hello, i created a test on my local machine
`  'refuses to construct IPv4 address with trailing and leading zeros': (test) ->
      test.equal(ipaddr.IPv4.isValidFourPartDecimal('000000192.168.100.2'), false)
      test.equal(ipaddr.IPv4.isValidFourPartDecimal('192.0000168.100.2'), false)
      test.equal(ipaddr.IPv4.isValidFourPartDecimal('192.168.100.00000002'), false)
      test.equal(ipaddr.IPv4.isValidFourPartDecimal('192.168.100.20000000'), false)
      test.done() `

all of it passed. Do you think its good? I also covered trailing zeros.

**Comment by whitequark** [comment]
Yep, looks good

**Comment by johnfrades** [comment]
Hello, thanks for the link, i followed the guide but im stuck here

**git pull upstream master && git push origin master**

my terminal
`$ git pull upstream master && git push origin master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by johnfrades** [comment]
> origin  https://github.com/whitequark/ipaddr.js.git (fetch)
> origin  https://github.com/whitequark/ipaddr.js.git (push)
> upstream        git@github.com:whitequark/ipaddr.js.git (fetch)
> upstream        git@github.com:whitequark/ipaddr.js.git (push)

**Comment by whitequark** [comment]
You can't pull or push from/to this repository using ssh (the `git@` lines) because, well, it's mine. You probably want `https://github.com/whitequark/ipaddr.js.git` as `upstream` and `git@github.com:johnfrades/ipaddr.js.git` as `origin`. Try this:
```
git remote rm origin
git remote rm upstream
git remote add upstream https://github.com/whitequark/ipaddr.js.git
git remote add origin git@github.com:johnfrades/ipaddr.js.git
git push origin master
```

**Comment by johnfrades** [comment]
hello, sorry i still can't make it work

```
$ git push origin master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by whitequark** [comment]
Did you set up an SSH key? It's in https://github.com/settings/keys.

**Comment by johnfrades** [comment]
Thank you so much! It was my 1st pull request in my whole life. :)
